const drills = [
  {
    name: "Pull Buoy Pull",
    focus: "Arm pull isolation",
    desc: "Use a pull buoy between your legs to eliminate the kick. Lets you focus entirely on the pull — outsweep, insweep, and forward extension.",
  },
  {
    name: "Kick on Back",
    focus: "Kick technique",
    desc: "Kick breaststroke while lying on your back, so you can look down and watch your feet. Check that heels come up narrow and feet flex outward on the drive.",
  },
  {
    name: "Two-Kicks One-Pull",
    focus: "Timing",
    desc: "Perform two kicks for every one arm pull. Exaggerates the glide phase and forces you to feel the momentum generated by the kick before pulling.",
  },
  {
    name: "Glide Extension",
    focus: "Reducing drag",
    desc: "After each stroke cycle, hold the streamlined glide position for a full count before beginning the next pull. Builds awareness of drag and momentum.",
  },
  {
    name: "Head-Up Breaststroke",
    focus: "Balance & sighting",
    desc: "Swim breaststroke with your head lifted above the waterline. Develops balance and is useful for open-water sighting skills.",
  },
  {
    name: "Undulation Drill",
    focus: "Body wave",
    desc: "Focus on an exaggerated head-dip and hip-rise during the stroke. The undulating body wave reduces frontal resistance and drives the kick.",
  },
];

export default function BreaststrokePage() {
  return (
    <div className="min-h-full bg-gradient-to-br from-sky-50 via-cyan-50 to-teal-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 px-6 py-16">
      <div className="max-w-5xl mx-auto">
        <a
          href="/strokes"
          className="text-sm font-medium text-cyan-600 dark:text-cyan-400 hover:underline mb-8 inline-block"
        >
          ← All strokes
        </a>

        <div className="mb-12">
          <h1 className="text-4xl font-bold tracking-tight text-slate-900 dark:text-slate-50 mb-3">
            🐸 Breaststroke
          </h1>
          <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl leading-relaxed">
            Breaststroke is the most technical of the four strokes. The pull-breathe-kick-glide
            cycle must be timed precisely — too much overlap creates drag, too long a glide loses
            momentum. Mastering the timing is what separates good breaststroke swimmers from great
            ones.
          </p>
        </div>

        <h2 className="text-2xl font-semibold text-slate-900 dark:text-slate-50 mb-6">Drills</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {drills.map(({ name, focus, desc }) => (
            <div key={name} className="rounded-2xl border border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 p-6">
              <span className="inline-block rounded-full bg-cyan-50 dark:bg-cyan-500/10 px-3 py-0.5 text-xs font-medium text-cyan-700 dark:text-cyan-400 mb-3">
                {focus}
              </span>
              <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50 mb-2">
                {name}
              </h3>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
